prtasm.o: prtasm.cpp
	g++ prtasm.cpp -c -o prtasm.o -Wall

prtasm: r5900.o prtasm.o
	g++ prtasm.o ./inscodec/codec.o ./inscodec/disas.o -o prtasm

preprocessor: preprocessor.cpp
	g++ preprocessor.cpp -o preprocessor -Wall

all: prtasm preprocessor


mipsincs: simpgen mips5900.txt
	./simpgen -i mips5900.txt -o mips5900

cleanobj:
	rm *.o *.obj

cleanall:
	rm *.o simpgen prtasm mips5900_*.inc
